#!/bin/bash

# Install Paper icon theme from PPA
function install_oracle_java {
	NAME="Snwh Paper Theme"
	PACKAGE="paper-icon-theme"
	# Do not include the "ppa:" bit, it will break other functions
	PPA="snwh/ppa"
	# Add PPA repository
	add_launchpad_ppa "$NAME" "$PPA" install_thirdparty
	# check exit status
	if [ $? = 0 ]; then
		# Install package
		install_package "$NAME" "$PACKAGE" install_thirdparty
	else
		# Cancelled
		echo_message info "Installation of $NAME cancelled."
		# return
		install_thirdparty
	fi
}
